name: "Check Author"
description: "Checks if the author is in the specified team in the Zaperex-Test-Org organization"

inputs:
  author:
    description: "The author to check"
    required: true
  team:
    description: "The team to check in the Zaperex-Test-Org organization"
    required: true

outputs:
  is_team_member:
    description: "Whether the specified author is in the specified team"
    value: ${{ steps.check.outputs.is_team_member }}

runs:
  using: "composite"
  steps:
    - name: Check if author is in the team
      id: check
      shell: bash
      run: |
        echo "Checking if ${{ inputs.author }} is in ${{ inputs.team }} team..."
        
        team_members=$(gh api "/orgs/Zaperex-Test-Org/teams/${{ inputs.team }}/members" --jq '.[].login' 2>/dev/null || echo "")
        
        # Convert space-separated list to newline-separated and check for exact match
        # Using grep with fixed string (`-F`) and exact line match (^$ or `-x`) for security
        author="${{ inputs.author }}"
        if echo "$team_members" | tr ' ' '\n' | grep -Fxq "$author"; then
          echo "✓ Author $author is in the ${{ inputs.team }} team"
          echo "is_team_member=true" >> $GITHUB_OUTPUT
        else
          echo "✗ Author $author is not in the ${{ inputs.team }} team"
          echo "is_team_member=false" >> $GITHUB_OUTPUT
        fi
