name: BuildKit Version and build-push-action@v6 Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-buildkit-version:
    runs-on: ubuntu-latest
    name: Test BuildKit Version with build-push-action@v6
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect Docker Buildx - Default Builder
        run: |
          set -x
          echo "=== Docker Buildx Default Builder Info ==="
          docker buildx ls
          echo ""
          echo "=== Current Builder Details ==="
          docker buildx inspect
          echo ""
          echo "=== Current Builder with Bootstrap ==="
          docker buildx inspect --bootstrap
          echo ""
      - name: Test build-push-action@v6 with BuildKit
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: test-buildkit:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/test-image.tar

      - name: Post-Build BuildKit Information
        run: |
          set -x
          echo "=== Post-Build BuildKit Status ==="
          docker buildx ls
          echo ""
          echo "=== Final Builder Inspection ==="
          docker buildx inspect
          echo ""
          echo "=== Build History (if available) ==="
          docker buildx du || echo "Build disk usage not available"

      - name: Test Built Image
        run: |
          set -x
          echo "=== Loading and Testing Built Image ==="
          docker load -i /tmp/test-image.tar
          echo "=== Running Test Container ==="
          docker run --rm test-buildkit:latest
          echo "=== Image Info ==="
          docker image inspect test-buildkit:latest --format '{{json .}}' | jq '.Config.Labels, .Architecture, .Os' || docker image inspect test-buildkit:latest


