name: On Workflow Run
on:
  workflow_run:
    workflows: ['PR Trigger']
    types: [completed]

env:
  REGISTRY: quay.io

jobs:
  publish-image:
    name: Publish Container Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      issues: write
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR number from workflow run
        id: get-pr
        run: |
          PR_NUMBER=$(echo '${{ toJson(github.event.workflow_run.pull_requests) }}' | jq -r '.[0].number // empty')
          FULL_SHA="${{ github.event.workflow_run.head_sha }}"
          SHORT_SHA=$(echo "$FULL_SHA" | cut -c1-8)
          if [ -n "$PR_NUMBER" ]; then
            echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "short-sha=$SHORT_SHA" >> $GITHUB_OUTPUT
            echo "artifact-name=container-image-pr-$PR_NUMBER-$SHORT_SHA" >> $GITHUB_OUTPUT
          else
            echo "No PR found in workflow run"
            exit 1
          fi

      # - name: print-github-stuff
      #   run: |
      #     echo '${{ toJson(github) }}' | jq .

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.get-pr.outputs.artifact-name }}
          path: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Load image and prepare for push
        id: load-image
        run: |
          # Load the image from tar
          podman load -i artifacts/image.tar
          
          # Read the image name and tags
          IMAGE_NAME=$(cat artifacts/image-name.txt)
          TAGS=$(cat artifacts/tags.txt)
          
          echo "image-name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "$TAGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # List loaded images for verification
          podman images

      - name: Push to registry
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.load-image.outputs.tags }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Comment the image pull link
        if: ${{ steps.get-pr.outputs.pr-number }}
        uses: actions/github-script@v7
        with:
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];
            if (!pullRequest) {
              console.log('No pull request found in workflow_run event');
              return;
            }
            
            const prNumber = pullRequest.number;
            const imageName = '${{ steps.load-image.outputs.image-name }}';
            const shortSha = '${{ steps.get-pr.outputs.short-sha }}';
            
            const imageUrls = [
              `${imageName}:pr-${prNumber}`,
              `${imageName}:pr-${prNumber}-${shortSha}`
            ];
            
            const imageUrlsText = imageUrls.map(url => `* [\`${url}\`](https://${url})`).join('\n');
            
            const body = '🚀 **Container Image Published**\n\n' +
                        'The image has been built and pushed to Quay.io:\n' +
                        imageUrlsText + '\n\n' +
                        'You can pull the image using:\n' +
                        '```bash\n' +
                        `podman pull ${imageUrls[0]}\n` +
                        '```';
            
            await github.rest.issues.createComment({
              issue_number: pullRequest.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

