name: On Workflow Run
on:
  workflow_run:
    workflows: ['PR Trigger']
    types: [completed]

jobs:
  do-stuff:
    name: Do Stuff
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cat
        run: |
          cat README.md
      - name: Sleep
        run: |
          sleep 10s

      - name: print-event
        run: |
          echo "${{ toJson(github.event) }}"

      - name: Comment the image pull link
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The image is available at:\n* [`quay.io/rhdh-community/rhdh:pr-${{ github.event.workflow_run.pull_requests[0].number }}`](https://quay.io/rhdh-community/rhdh:pr-${{ github.event.workflow_run.pull_requests[0].number }}) or\n* [`quay.io/rhdh-community/rhdh:pr-${{ github.event.workflow_run.pull_requests[0].number }}-${{ env.SHORT_SHA }}`](https://quay.io/rhdh-community/rhdh:pr-${{ github.event.workflow_run.pull_requests[0].number }}-${{ env.SHORT_SHA }})'
            })

