name: PR Trigger
on:
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  do-stuff: 
    name: Do Stuff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sleep_timer: [1, 10, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Sleep
        run: |
          echo "Sleeping for ${{ matrix.sleep_timer }}s"
          sleep ${{ matrix.sleep_timer }}s
      - name: Cat
        run: |
          cat README.md