name: PR Trigger
on:
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.event.pull_request.head.ref }}
  cancel-in-progress: true

env:
  REGISTRY: quay.io

jobs:
  build-image: 
    name: Build Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: set-short-sha
        run: |
          REF=${{ github.event.pull_request.head.ref }}
          SHORT_SHA=$(git rev-parse --short=8 $REF)
          echo "SHORT_SHA: $SHORT_SHA"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
      - name: Build Image with Buildah 
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/my-test-organization/test-registry 
          tags: |
            pr-${{ github.event.number }}
            pr-${{ github.event.number }}-${{ env.SHORT_SHA }}
          containerfiles: |
            ./Dockerfile

      - name: Save image to tar
        run: |
          podman images
          mkdir -p artifacts
          podman save ${{ steps.build-image.outputs.image }}:pr-${{ github.event.number }} ${{ steps.build-image.outputs.image }}:pr-${{ github.event.number }}-${{ env.SHORT_SHA }} -o artifacts/image.tar
          echo "pr-${{ github.event.number }}" > artifacts/tags.txt
          echo "pr-${{ github.event.number }}-${{ env.SHORT_SHA }}" >> artifacts/tags.txt
          echo "${{ steps.build-image.outputs.image }}" > artifacts/image-name.txt

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-image-pr-${{ github.event.number }}-${{ env.SHORT_SHA }}
          path: artifacts/
          retention-days: 7

      - name: print_github_stuff
        run: |
          echo '${{ toJson(github) }}' | jq .

      - name: Finish
        run: |
          echo "Image built and uploaded as artifact"
