name: PR Trigger
on:
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  build-image: 
    name: Build Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: debug
        run: |
          echo "SHORT_SHA: ${{ env.SHORT_SHA }}"
      - name: Build Image with Buildah 
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: test-app
          tags: |
            pr-${{ github.event.number }}
            ${{ github.event.pull_request.head.sha }}
          containerfiles: |
            ./Dockerfile

      - name: Save image to tar
        run: |
          mkdir -p artifacts
          buildah push ${{ steps.build-image.outputs.image }}:pr-${{ github.event.number }} oci-archive:artifacts/image.tar
          echo "pr-${{ github.event.number }}" > artifacts/tags.txt
          echo "${{ github.event.pull_request.head.sha }}" >> artifacts/tags.txt
          echo "${{ steps.build-image.outputs.image }}" > artifacts/image-name.txt

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-image-pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}
          path: artifacts/
          retention-days: 7

      - name: print_github_stuff
        run: |
          echo '${{ toJson(github) }}' | jq .

      - name: Finish
        run: |
          echo "Image built and uploaded as artifact"
