name: Test Volume Mounting - Docker vs Podman

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker-volumes:
    runs-on: ubuntu-latest
    name: Test Docker Volume Mounting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test directory structure
        run: |
          set -x 
          mkdir -p ./test-cache/docker-test
          echo "Initial host file" > ./test-cache/docker-test/host-file.txt
          ls -la ./test-cache/

      - name: Test Docker volume mounting
        run: |
          set -x 
          echo "=== Testing Docker Volume Mounting ==="
          
          # Run container that creates files in mounted volume
          docker run --rm \
            -v "$PWD/test-cache:/mounted-cache:z" \
            -w /mounted-cache \
            alpine:latest sh -c '
              echo "=== Inside Docker container ==="
              ls -la /mounted-cache/
              
              # Create files and directories
              mkdir -p /mounted-cache/docker-created/subdir
              echo "Created by Docker container" > /mounted-cache/docker-created/container-file.txt
              echo "Another file" > /mounted-cache/docker-created/subdir/nested-file.txt
              
              # Set permissions
              chmod 755 /mounted-cache/docker-created
              chmod 644 /mounted-cache/docker-created/container-file.txt
              
              echo "=== Files created in container ==="
              ls -la /mounted-cache/
              ls -la /mounted-cache/docker-created/
              
              # Show ownership
              echo "=== Ownership inside container ==="
              ls -ln /mounted-cache/docker-created/
            '

      - name: Verify Docker volume persistence
        run: |
          set -x 
          echo "=== Verifying Docker volume persistence on host ==="
          ls -la ./test-cache/
          
          if [ -d "./test-cache/docker-created" ]; then
            echo "✅ Docker-created directory exists on host"
            ls -la ./test-cache/docker-created/
            
            if [ -f "./test-cache/docker-created/container-file.txt" ]; then
              echo "✅ Docker-created file exists on host"
              cat ./test-cache/docker-created/container-file.txt
            else
              echo "❌ Docker-created file NOT found on host"
            fi
          else
            echo "❌ Docker-created directory NOT found on host"
          fi
          
          echo "=== Host ownership ==="
          ls -ln ./test-cache/docker-created/ || echo "Directory not accessible"

  test-podman-volumes:
    runs-on: ubuntu-latest
    name: Test Podman Volume Mounting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Create test directory structure
        run: |
          mkdir -p ./test-cache/podman-test
          echo "Initial host file" > ./test-cache/podman-test/host-file.txt
          ls -la ./test-cache/

      - name: Test Podman volume mounting
        run: |
          set -x 
          echo "=== Testing Podman Volume Mounting ==="
          
          # Run container that creates files in mounted volume
          podman run --rm \
            -v "$PWD/test-cache:/mounted-cache:z" \
            -w /mounted-cache \
            alpine:latest sh -c '
              echo "=== Inside Podman container ==="
              ls -la /mounted-cache/
              
              # Create files and directories
              mkdir -p /mounted-cache/podman-created/subdir
              echo "Created by Podman container" > /mounted-cache/podman-created/container-file.txt
              echo "Another file" > /mounted-cache/podman-created/subdir/nested-file.txt
              
              # Set permissions
              chmod 755 /mounted-cache/podman-created
              chmod 644 /mounted-cache/podman-created/container-file.txt
              
              echo "=== Files created in container ==="
              ls -la /mounted-cache/
              ls -la /mounted-cache/podman-created/
              
              # Show ownership
              echo "=== Ownership inside container ==="
              ls -ln /mounted-cache/podman-created/
            '

      - name: Verify Podman volume persistence
        run: |
          set -x 
          echo "=== Verifying Podman volume persistence on host ==="
          ls -la ./test-cache/
          
          if [ -d "./test-cache/podman-created" ]; then
            echo "✅ Podman-created directory exists on host"
            ls -la ./test-cache/podman-created/
            
            if [ -f "./test-cache/podman-created/container-file.txt" ]; then
              echo "✅ Podman-created file exists on host"
              cat ./test-cache/podman-created/container-file.txt
            else
              echo "❌ Podman-created file NOT found on host"
            fi
          else
            echo "❌ Podman-created directory NOT found on host"
          fi
          
          echo "=== Host ownership ==="
          ls -ln ./test-cache/podman-created/ || echo "Directory not accessible"


  test-permissions-and-selinux:
    runs-on: ubuntu-latest
    name: Test Permissions and SELinux Context
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Check SELinux status
        run: |
          set -x 
          echo "=== SELinux Status ==="
          sestatus || echo "SELinux not available"
          getenforce || echo "SELinux not enforcing"

      - name: Test different volume mount options
        run: |
          set -x 
          echo "=== Testing different volume mount options ==="
          
          mkdir -p ./test-volumes
          
          # Test without :z
          echo "--- Without :z flag ---"
          docker run --rm -v "$PWD/test-volumes:/test" alpine:latest sh -c '
            mkdir -p /test/no-z
            echo "no-z test" > /test/no-z/file.txt
          ' || echo "Docker without :z failed"
          ls -la ./test-volumes/ || echo "No directory created"
          
          # Test with :z
          echo "--- With :z flag ---"
          docker run --rm -v "$PWD/test-volumes:/test:z" alpine:latest sh -c '
            mkdir -p /test/with-z
            echo "with-z test" > /test/with-z/file.txt
          ' || echo "Docker with :z failed"
          ls -la ./test-volumes/ || echo "No directory created"
          
          # Test with :Z
          echo "--- With :Z flag ---"
          docker run --rm -v "$PWD/test-volumes:/test:Z" alpine:latest sh -c '
            mkdir -p /test/with-Z
            echo "with-Z test" > /test/with-Z/file.txt
          ' || echo "Docker with :Z failed"
          ls -la ./test-volumes/ || echo "No directory created"

      - name: Compare Docker vs Podman with same volume options
        run: |
          set -x 
          echo "=== Comparing Docker vs Podman ==="
          
          mkdir -p ./comparison-test
          
          echo "--- Docker test ---"
          docker run --rm -v "$PWD/comparison-test:/test:z" alpine:latest sh -c '
            echo "docker-test" > /test/docker-created.txt
            ls -la /test/
          '
          
          echo "--- Podman test ---"
          podman run --rm -v "$PWD/comparison-test:/test:z" alpine:latest sh -c '
            echo "podman-test" > /test/podman-created.txt
            ls -la /test/
          '
          
          echo "--- Final state on host ---"
          ls -la ./comparison-test/
          echo "Docker file content:" && cat ./comparison-test/docker-created.txt || echo "Docker file not found"
          echo "Podman file content:" && cat ./comparison-test/podman-created.txt || echo "Podman file not found"

  test-nonexistent-directory-mounting:
    runs-on: ubuntu-latest
    name: Test Mounting Non-Existent Directories
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Test Docker with non-existent directory
        run: |
          set -x 
          echo "=== Testing Docker with non-existent directory ==="
          
          # Ensure the directory doesn't exist
          rm -rf ./nonexistent-docker-test
          
          echo "--- Before Docker run ---"
          ls -la . | grep nonexistent || echo "No nonexistent directories found (expected)"
          
          # Try to mount a non-existent directory
          echo "--- Running Docker with non-existent mount point ---"
          docker run --rm \
            -v "$PWD/nonexistent-docker-test:/test-mount:z" \
            alpine:latest sh -c '
              echo "=== Inside Docker container ==="
              ls -la /
              echo "Mount point /test-mount:"
              ls -la /test-mount/ || echo "Mount point not accessible"
              
              echo "Attempting to create files in mount point..."
              mkdir -p /test-mount/created-in-container
              echo "Docker created this file" > /test-mount/created-in-container/test.txt
              echo "Files created:"
              ls -la /test-mount/
              ls -la /test-mount/created-in-container/ || echo "Subdir not accessible"
            ' || echo "Docker run failed"
          
          echo "--- After Docker run ---"
          if [ -d "./nonexistent-docker-test" ]; then
            echo "✅ Docker created the non-existent directory on host"
            ls -la ./nonexistent-docker-test/
            if [ -f "./nonexistent-docker-test/created-in-container/test.txt" ]; then
              echo "✅ Files created in container are accessible on host"
              cat ./nonexistent-docker-test/created-in-container/test.txt
            else
              echo "❌ Files created in container are NOT accessible on host"
            fi
          else
            echo "❌ Docker did NOT create the non-existent directory on host"
          fi

      - name: Test Podman with non-existent directory
        run: |
          set -x 
          echo "=== Testing Podman with non-existent directory ==="
          
          # Ensure the directory doesn't exist
          rm -rf ./nonexistent-podman-test
          
          echo "--- Before Podman run ---"
          ls -la . | grep nonexistent || echo "No nonexistent directories found (expected)"
          
          # Try to mount a non-existent directory
          echo "--- Running Podman with non-existent mount point ---"
          podman run --rm \
            -v "$PWD/nonexistent-podman-test:/test-mount:z" \
            alpine:latest sh -c '
              echo "=== Inside Podman container ==="
              ls -la /
              echo "Mount point /test-mount:"
              ls -la /test-mount/ || echo "Mount point not accessible"
              
              echo "Attempting to create files in mount point..."
              mkdir -p /test-mount/created-in-container
              echo "Podman created this file" > /test-mount/created-in-container/test.txt
              echo "Files created:"
              ls -la /test-mount/
              ls -la /test-mount/created-in-container/ || echo "Subdir not accessible"
            ' || echo "Podman run failed"
          
          echo "--- After Podman run ---"
          if [ -d "./nonexistent-podman-test" ]; then
            echo "✅ Podman created the non-existent directory on host"
            ls -la ./nonexistent-podman-test/
            if [ -f "./nonexistent-podman-test/created-in-container/test.txt" ]; then
              echo "✅ Files created in container are accessible on host"
              cat ./nonexistent-podman-test/created-in-container/test.txt
            else
              echo "❌ Files created in container are NOT accessible on host"
            fi
          else
            echo "❌ Podman did NOT create the non-existent directory on host"
          fi

      - name: Test nested non-existent path mounting
        run: |
          set -x 
          echo "=== Testing nested non-existent path mounting ==="
          
          # Clean up any existing directories
          rm -rf ./deeply/nested/nonexistent
          
          echo "--- Testing Docker with deeply nested non-existent path ---"
          docker run --rm \
            -v "$PWD/deeply/nested/nonexistent:/deep-mount:z" \
            alpine:latest sh -c '
              echo "=== Inside Docker container (nested test) ==="
              ls -la /deep-mount/ || echo "Deep mount not accessible"
              echo "Creating file in deep mount..."
              echo "Docker deep nested file" > /deep-mount/deep-test.txt
              ls -la /deep-mount/
            ' || echo "Docker deep nested run failed"
          
          echo "--- After Docker deep nested run ---"
          if [ -f "./deeply/nested/nonexistent/deep-test.txt" ]; then
            echo "✅ Docker created deeply nested directory structure"
            echo "Directory structure:"
            find ./deeply -type d
            echo "File content:"
            cat ./deeply/nested/nonexistent/deep-test.txt
          else
            echo "❌ Docker did NOT create deeply nested directory structure"
          fi
          
          echo "--- Testing Podman with deeply nested non-existent path ---"
          podman run --rm \
            -v "$PWD/deeply/nested/nonexistent:/deep-mount:z" \
            alpine:latest sh -c '
              echo "=== Inside Podman container (nested test) ==="
              ls -la /deep-mount/ || echo "Deep mount not accessible"
              echo "Creating file in deep mount..."
              echo "Podman deep nested file" > /deep-mount/deep-test-podman.txt
              ls -la /deep-mount/
            ' || echo "Podman deep nested run failed"
          
          echo "--- After Podman deep nested run ---"
          if [ -f "./deeply/nested/nonexistent/deep-test-podman.txt" ]; then
            echo "✅ Podman handled deeply nested directory structure"
            echo "Files in nested directory:"
            ls -la ./deeply/nested/nonexistent/
          else
            echo "❌ Podman did NOT handle deeply nested directory structure correctly"
          fi

      - name: Test mounting non-existent directory with specific permissions
        run: |
          set -x 
          echo "=== Testing non-existent directory with permission operations ==="
          
          rm -rf ./permission-test-dir
          
          echo "--- Testing permission setting in non-existent mounted directory ---"
          docker run --rm \
            -v "$PWD/permission-test-dir:/perm-test:z" \
            alpine:latest sh -c '
              echo "=== Setting permissions in mounted non-existent dir ==="
              mkdir -p /perm-test/subdir
              echo "Permission test file" > /perm-test/subdir/file.txt
              
              # Try to set specific permissions
              chmod 755 /perm-test/subdir
              chmod 644 /perm-test/subdir/file.txt
              
              echo "Permissions inside container:"
              ls -la /perm-test/
              ls -la /perm-test/subdir/
            '
          
          echo "--- Checking permissions on host ---"
          if [ -d "./permission-test-dir" ]; then
            echo "✅ Permission test directory created"
            echo "Host permissions:"
            ls -la ./permission-test-dir/
            ls -la ./permission-test-dir/subdir/ || echo "Subdir not accessible"
            
            echo "Numeric permissions:"
            stat -c "%a %n" ./permission-test-dir/subdir/* || echo "Cannot stat files"
          else
            echo "❌ Permission test directory NOT created"
          fi
